### ISSUE TITLE
You're really good.

### ISSUE THREAD

**Issue by jax-explorer** [logtd/ComfyUI-LTXTricks#1]
Hi, I'm the founder of comfyonline.app.
You did a great job RF is a very nice thought, both the pictures and the video. May I ask if there is anything I can do to help you?
If you need GPU or other help, let me know and will help you as much as I can!
It's really very nice.

**Comment by logtd** [comment]
Hi, thank you!

Feel free to DM me on Discord (@Juxtapoz) or on Twitter (@logtdx)
