### ISSUE TITLE
After installing ltxtricks nodes, the original ltx i2v workflow no longer responded to the input images

### ISSUE THREAD

**Issue by gtbloody** [logtd/ComfyUI-LTXTricks#13]
![image](https://github.com/user-attachments/assets/6b272b42-7018-4ff6-9135-847c7c784fe0)
After installing ltxtricks nodes, the original ltx i2v workflow no longer responded to the input images, even though I didn't use any nodes from ltxtricks. The workflow returned to normal after uninstalling ltxtricks. Is this a feature or a bug?
uninstall ltxtricks like this↓↓↓
![573cee6658663a9772da6276b43d1398](https://github.com/user-attachments/assets/185fb8a4-b9cd-4ab3-b149-1892b5a14806)

**Comment by gtbloody** [comment]
![e7ed74fff8c64966dc74a2c601faa923](https://github.com/user-attachments/assets/af2d6551-48d6-468b-8793-b6e27e911dfc)
After installing ltxtricks nodes，like this↑↑↑

**Comment by logtd** [comment]
Hi, this should be fixed now. Feel free to reopen if not after you update
