### ISSUE TITLE
Question: Is it possible to use image as end of frame (inverse of i2v) ?

### ISSUE THREAD

**Issue by x4080** [logtd/ComfyUI-LTXTricks#14]
Is it possible ?

**Comment by cheezecrisp** [comment]
How about reversing the order of the frame batch?

**Comment by x4080** [comment]
@cheezecrisp do you mean reversing in video editing software ?

**Comment by cheezecrisp** [comment]
> @cheezecrisp do you mean reversing in video editing software ?

Yes, and some nodes should also make it in comfyui, just like "reverse image batch" of kjnodes.

**Comment by x4080** [comment]
@cheezecrisp Thanks for the tip
