### ISSUE TITLE
Question about uploading image

### ISSUE THREAD

**Issue by git523** [logtd/ComfyUI-LTXTricks#2]
In the example workflows, I was not able to find the node to upload image, only the node to upload videos. Could you share a screenshot about how to upload an image (like the Shrek image in the RF-Inversion example)? This might be a stupid question, as I am just started learning comfyui. Thank you very much for sharing the wonderful tool!

**Comment by logtd** [comment]
You can use the `Add LTX Guiding Latent` node to set the first latent to an encoded frame. For an example of using that node check out the interpolation workflow. Just use a single one, index 0, insert off. Only use it on the "Reverse Sampler" part.

**Comment by git523** [comment]
Thank you very much for the instruction. I got it set up (screenshot attached below), but got this error message when running. Not sure where I made a mistake....

![error](https://github.com/user-attachments/assets/53b0084d-6939-401a-9768-f0b325b35a3a)


got prompt
  0%|                                                                                                                                                                                                                                                                                                  | 0/30 [00:00<?, ?it/s]
!!! Exception during processing !!! The size of tensor a (3) must match the size of tensor b (7) at non-singleton dimension 2
Traceback (most recent call last):
  File "C:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\pinokio\api\comfy.git\app\comfy_extras\nodes_custom_sampler.py", line 476, in sample
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
  File "C:\pinokio\api\comfy.git\app\comfy\sample.py", line 48, in sample_custom
    samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\pinokio\api\comfy.git\app\comfy\samplers.py", line 753, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\pinokio\api\comfy.git\app\comfy\samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\pinokio\api\comfy.git\app\comfy\samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\pinokio\api\comfy.git\app\comfy\samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\pinokio\api\comfy.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-LTXTricks\nodes\rectified_sampler_nodes.py", line 106, in sample_reverse
    conditional_vector_field = (y0-X)/(1-t_i)
RuntimeError: The size of tensor a (3) must match the size of tensor b (7) at non-singleton dimension 2

**Comment by logtd** [comment]
[This workflow](https://github.com/logtd/ComfyUI-LTXTricks/blob/main/example_workflows/example_ltx_iv2v.json) may help you. I can't tell but it looks like you've got your latents set up wrong

**Comment by git523** [comment]
Yes indeed. The iv2v workflow helped a lot, I copied the set up and now it is working. Somehow I was not able to get the background copied over (always blurry and modified in the generated video). I will tweak more to learn about it. Thanks again for the tool and your kind help.
