### ISSUE TITLE
Question regarding vram requirements?

### ISSUE THREAD

**Issue by SAT431** [logtd/ComfyUI-LTXTricks#3]
Do video to video require same vram as image to video workflow. I mean I have 12gb vram so can I run video to video

**Comment by logtd** [comment]
I saw someone with 12gb run the v2v workflow so it should be possible

**Comment by SAT431** [comment]
Thank you

**Comment by bjornwed** [comment]
Can confirm I've been running it sucessfully with as little as 6GB VRAM on an RTX 3060 on my laptop (yes, I'm poor :)). So far, I haven't had any out-of-memory issues, although it's (obviously) not that fast.

Any guidance or more examples on inversion and/or iv2v would be terrific. For example, on the Shrek example for inversion, how many steps for unsampling/reverse sampling, gamma (assume 0.5 would be a good starting point) and finally reverse eta, start-stop? Any other settings to pay extra attention to, for example cfg etc. 

I got my "Shrek" to move, although the video is of a person dancing, he's babbling about something (I have no idea what he's talking about) so, it's kinda funny outcome.

Cheers and thanks for the amazing work, it's really mind-blowing looking back 10-12 months with SD1.5 and LCM etc.

**Comment by logtd** [comment]
@bjornwed 

iv2v is pretty experimental and results will vary greatly. The model just wasn't meant for this so it doesn't fair well

For anything else, you mention most of the important variables. It just takes some time to learn how it affects the outcome. Each input and desired outcome will take some tuning. Luckily LTX is fast.

Once LTX releases additional models I may write some further docs on what variables do internally.

**Comment by Johnreidsilver** [comment]
I'm super impressed, running on 6GB VRAM laptop RTX3060, 32GB RAM no swap is used. Just had to lower the resolution to 512x256 and I find it extremely fast compared with free online models.

I always run comfy with lowvram option:
python3 main.py --lowvram

not sure, but these might also help:
--use-split-cross-attention --preview-method auto

Just wanted to thank the team behind this project and the comfy adaptations!
